config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path



urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path('store/', include('my_awesome_project.store.urls')),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

my_awesome_project/store/urls.py
from django.urls import path
from .views import all_categories, products_by_category, product_detail, checkout, payment, order_item_endpoint, order_item_delete_endpoint
from django.views.generic import TemplateView

app_name = "store"
urlpatterns = [
    path("", all_categories, name="all_categories"),
    path("cart/", TemplateView.as_view(template_name="store/cart.html"), name="cart_view"),

    path('checkout/<uuid:uuid>/', checkout, name="checkout"),
    path('payment/<uuid:uuid>/', payment, name="payment"),

    path('<slug:slug_cat>/', products_by_category, name="products_by_category"),
    path('<slug:slug_cat>/<slug:slug_prod>/', product_detail, name="product_detail"),

    path('item/<slug:slug_cat>/<slug:slug_prod>/', order_item_endpoint, name="order_item_endpoint"),
    path('delete/<slug:slug_cat>/<slug:slug_prod>/<str:str>', order_item_delete_endpoint, name="order_item_delete_endpoint"),
]

my_awesome_project/store/models.py
from django.db import models
from datetime import date
from django.utils.text import slugify
import uuid
from django.core.validators import MinValueValidator, MaxValueValidator
from django.shortcuts import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)
    image= models.ImageField(upload_to='categories/')
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    @staticmethod
    def get_all_categories():
        return Category.objects.all()

    def get_absolute_url(self):
        return reverse("store:products_by_category", kwargs={
            'slug_cat': self.slug
        })

    def __str__(self):
        return self.name

    class Meta:
        # order by id
        ordering = ('id',)
        verbose_name_plural = 'Categories'


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True, editable=False)
    price= models.DecimalField(default=0, decimal_places=2, max_digits=10)
    category= models.ForeignKey(Category,on_delete=models.CASCADE)
    description= models.TextField(max_length=500, blank=True, null= True)
    image= models.ImageField(upload_to='uploads/products/')
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("store:product_detail", kwargs={
            'slug_cat': self.category.slug,
            'slug_prod': self.slug
        })

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def get_all_products_by_category_slug(slug_cat):
        category = Category.objects.get(slug=slug_cat)
        return Product.objects.filter(category=category)
    
    def __str__(self):
        return self.name


class Order(models.Model):
    # device id generated by javascript, use this instead of user
    device = models.CharField(max_length=100, editable=False)
    name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=100, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    # when the customer indicates that he paid for the order, completed = True
    completed = models.BooleanField(default=False)
    # when the seller confirms that the order was paid for, paid = True
    paid = models.BooleanField(default=False)
    # when the seller delivers the order, delivered = True
    delivered = models.BooleanField(default=False)
    # uuid will identify the order and will be included in the payment link
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    
    def __str__(self):
        return str(self.uuid)

    
    @property
    def get_cart_total(self):
        items = self.items.all()
        total = sum([item.get_total for item in items])
        return total

    @property
    def get_cart_items(self):
        items = self.items.all()
        total = sum([item.quantity for item in items])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = float(self.product.price) * int(self.quantity)
        return total
    
    def __str__(self):
        return str(self.product.name) + " - " + str(self.order.uuid) + " - " + str(self.quantity) + " - " + str(self.get_total)
    
    class Meta:
        ordering = ['-date_added']

my_awesome_project/store/views.py
from django.shortcuts import render, redirect
from .models import Category, Product, Order, OrderItem
from django.http import Http404
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required


# categories view
def all_categories(request):
    # check if the url is valid
    try:
        categories = Category.get_all_categories()
    except:
        raise Http404("Kažkas negerai.. ")
    return render(request, "store/all_categories.html", {"categories": categories})


def products_by_category(request, slug_cat):
    try:
        products = Product.get_all_products_by_category_slug(slug_cat)
    except:
        raise Http404("Tokių grybų neradome.. ")
    return render(request, "store/products_by_category.html", {"products": products})


def product_detail(request, slug_cat, slug_prod):
    # check if the url is valid
    try:
        device = request.COOKIES['device']
        category = Category.objects.get(slug=slug_cat)
        product = Product.objects.get(slug=slug_prod)
        order, created = Order.objects.get_or_create(device=device, completed=False)
    except Product.DoesNotExist or Category.DoesNotExist:
        raise Http404("Tokių grybų neradome.. ")
    # get the device id
    # when user visits this page, check the database if there is NOT completed order with this device id
    # if there is NOT, create a new order with this device id
    # if there is, get that order

    # once we have order, lets check if there is order item with this product, if there is change the quantity and the price accordingly
    try:
        order_item = order.items.get(product=product)
    except OrderItem.DoesNotExist:
        order_item = None
    return render(request, "store/product_detail.html", {"product": product, "order_item": order_item})


# one endpoint managing order items
@require_http_methods(["POST"])
def order_item_endpoint(request, slug_cat, slug_prod):
    try:
    # get the device id and order and the product
        device = request.COOKIES['device']
        order = Order.objects.get(device=device, completed=False)
        product = Product.objects.get(slug=slug_prod)
    except:
        raise Http404("Kažkas negerai.. ")
    #if the order item exists, i change the quantity, otherwise i create a new order item
    try:
        order_item = order.items.get(product=product)
        order_item.quantity = request.POST['quantity']
        order_item.save()
    except OrderItem.DoesNotExist:
        OrderItem.objects.create(product=product, order=order, quantity=request.POST['quantity'])

    return redirect('store:product_detail', slug_cat=slug_cat, slug_prod=slug_prod)


def order_item_delete_endpoint(request, slug_cat, slug_prod, str):
    print(str)
    try:
        device = request.COOKIES['device']
        order = Order.objects.get(device=device, completed=False)
        product = Product.objects.get(slug=slug_prod)
    except:
        raise Http404("Kažkas negerai.. ")
    try:
        order_item = order.items.get(product=product)
        order_item.delete()
    except OrderItem.DoesNotExist:
        pass

    # ultra quick fix how to manage redirects after cart is empty. so now if i can add any string to the button and pass that to the url, i can make one
    # endpoint for all order management oh wait i cant because i can only send get requests
    if str == "cart":

        if order.items.first() == None:
            return redirect('store:all_categories')
        else:
            return redirect('store:cart_view')

    elif str == "product":
        return redirect('store:product_detail', slug_cat=slug_cat, slug_prod=slug_prod)
    
    # if the string is not cart or product something is fishy so just return to categories
    else:
        return redirect('store:all_categories')


def checkout(request, uuid):
    order = Order.objects.get(uuid=uuid)
    
    if request.method == "POST":
        data = request.POST
        print(data)

        order.name = (data['firstName'] + " " + data['lastName'])
        order.email = data['email']
        order.phone = data['phoneNumber']
        order.address = (data['address1'] + " " + data['address2'])
        order.city = data['city']
        order.completed = True

        order.save()

        return redirect('store:payment', uuid=uuid)

    return render(request, "store/checkout.html")

def payment(request, uuid):
    order = Order.objects.get(uuid=uuid)

    if request.method == "POST":
        order.paid = True
        order.save()
        return redirect('store:all_categories')

    return render(request, "store/payment.html", {"order": order})

my_awesome_project/templates/store/all_categories.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 pt-3">
      <li class="breadcrumb-item active" aria-current="page">Kategorijos</li>
    </ol>
</nav>

<div class="container text-center color grow">
    <div class="row row-cols-1 row-cols-md-3 g-3 ">
        {% for category in categories %}
        <div class="col">
            <div class="card border-0">
                <a href="#"><img src="{{category.image.url}}" alt="jusciogrybai" class="card-img-top img-fluid shadow cover-img"></a>
                <div class="card-body">
                    <h5 class="card-title">{{category.name}}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

my_awesome_project/templates/store/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container grow">
    {% for item in nav_order.items.all %}
    <div class="container">
        <div class="list-group w-auto d-flex flex-row">
            <a href="{{item.product.get_absolute_url}}" class="list-group-item list-group-item-action d-flex gap-4" aria-current="true">
            <img src="{% static 'images/logos/mushroom-color.png' %}" width="40px" height="40px" alt="twbs" class="rounded-circle flex-shrink-0 my-auto">
            <div class="d-flex-inline align-items-center">
                <h6 class="my-auto text-decoration-underline">{{item.product.name}}</h6>
                <div class="d-flex align-items-center flex-row pt-2">
                  <span class="h6 my-auto">{{item.quantity}} x {{item.product.price}}€ = </span>
                  <span class="h6 my-auto">{{item.get_total}}€</span>
                </div>
            </div>
            </a>
            <a href="{% url 'store:order_item_delete_endpoint' item.product.category.slug item.product.slug 'cart' %}" class="text-dark text-decoration-none my-auto">
              <img src="{% static 'images/logos/no-stopping.png' %}" alt="twbs" width="32px" height="32px" class="rounded-circle flex-shrink-0">
            </a>
        </div>
        <hr style="border-top: 3px solid black">
    </div>
    {% endfor %}
    <div class="container d-flex justify-content-center pt-3">
      <a href="{% url 'store:checkout' nav_order.uuid %}" class="btn btn-outline-primary w-100">Suma: {{nav_order.get_cart_total}}€ </a>
      <img src="{% static 'images/logos/ok-hand.svg' %}" alt="jusciogrybai" class="ms-3" width="48" height="48">
    </div>  
  </div>
{% endblock %}

my_awesome_project/templates/store/checkout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h3>Jūsų užsakymas</h3>
    </div>

    <form method="POST" action="">
      {% csrf_token %}
    <div class="pt-3">
        <div class="row g-2">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">Vardas</label>
              <input name="firstName" type="text" class="form-control" id="firstName" placeholder="Tomas" required="required">
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Pavarde</label>
              <input name="lastName" type="text" class="form-control" id="lastName" placeholder="Mol" required="required">
            </div>


            <div class="col-12">
              <label for="email" class="form-label">Elektroninis paštas</label>
              <input name="email" type="email" class="form-control" id="email" placeholder="vardenas@pvz.com" required="required">
            </div>

            <div class="col-sm-6">
              <label for="address" class="form-label">Gatvė ir namo numeris</label>
              <input name="address1" type="text" class="form-control" id="address" placeholder="Molo gatvė 3" required="required">
            </div>

            <div class="col-sm-6">
              <label for="address2" class="form-label">Buto numeris</label>
              <input name="address2" type="text" class="form-control" id="address2" placeholder="Nr. 74" required="required">
            </div>

            <div class="col-sm-6">
              <label for="country" class="form-label">Miestas</label>
              <input name="city" type="text" class="form-control" id="address2" placeholder="Klaipėda" required="required">
            </div>

            <div class="col-sm-6">
              <label for="city" class="form-label">Numeris</label>
              <input name="phoneNumber" type="text" class="form-control" id="city" placeholder="860123123" required="required">
            </div>
        </div>

        <h4 class="my-3 ms-2">Mokėjimas</h4>

        <div class="my-3 ms-2">
            <div class="form-check">
              <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required="required">
              <label class="form-check-label" for="credit">Bankinis pavedimas</label>
            </div>
            <div class="form-check disabled">
              <input id="debit" name="paymentMethod" type="radio" class="form-check-input" disabled="">
              <label class="form-check-label" for="debit">Elektroninė bankininkystė</label>
            </div>
            <div class="form-check disabled">
              <input id="paypal" name="paymentMethod" type="radio" class="form-check-input disabled" disabled="">
              <label class="form-check-label" for="paypal">PayPal</label>
            </div>
            <div class="form-check disabled">
              <input id="paypal" name="paymentMethod" type="radio" class="form-check-input disabled" disabled="">
              <label class="form-check-label" for="paypal">Bitcoin</label>
            </div>
        </div>
        <div class="container d-flex justify-content-center pt-3">
            <input class="btn btn-outline-primary w-100" type="submit" value="Patvirtinti"></input>
            <img src="{% static 'images/logos/ok-hand.svg' %}" alt="jusciogrybai" class="ms-3" width="48" height="48">
        </div> 
    </div>
</div>
{% endblock %}

my_awesome_project/templates/store/payment.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container">
    <div class="py-5 text-center">
        <h3>Sąskaita</h3>
    </div>
    <div class="row g-5 pt-1">
      <div class="col-md-5 col-lg-4 order-md-last">
        <ul class="list-group mb-3">
          {% for item in order.items.all %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">{{item.product.name}}  {{item.quantity}}X</h6>
              <small class="text-muted">{{item.product.category}}</small>
            </div>
            <span class="text-muted">€{{item.get_total}}</span>
          </li>
          {% endfor %}
        </ul>
      </div>

      <div class="col-md-7 col-lg-8">
        <h5 class="mb-3 pb-1">Pervesti pardavėjui<strong class="px-3">€{{order.get_cart_total}}</strong></h5>
        <form method="POST" action="#">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6">
                Mindaugas Taranovskis
            </div>

            <div class="col-sm-6">
                LT137300010000561355
            </div>
          </div>

          <hr class="my-4 pb-5" style="border-top: 3px solid black">

          <h5 class="mb-3 pb-1">Nurodykite užsąkymo numerį mokėjimo paskirtyje </h5>

            <div class="row g-3">
                <div class="col-sm-6">
                    Užsakymo numeris
                </div>
    
                <div class="col-sm-6">
                    SDKND232D
                </div>
            </div>

          <hr class="my-4 pb-5" style="border-top: 3px solid black">

          <div class="container d-flex justify-content-center pt-3">
            <input class="btn btn-outline-primary w-100" type="submit" value="Atlikau mokėjimą !"></input>
            <img src="{% static 'images/logos/ok-hand.svg' %}" alt="jusciogrybai" class="ms-3" width="48" height="48">
         </div> 
        </form>
      </div>
    </div>
</div>
{% endblock %}

Atlikau mokėjimą !

my_awesome_project/templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}
<script src="https://unpkg.com/htmx.org@1.8.0"></script>

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-4 pt-1">
      <li class="breadcrumb-item"><a href="{% url 'store:all_categories' %}">Kategorijos</a></li>
      <li class="breadcrumb-item"><a href="{% url 'store:products_by_category' product.category.slug %}">Grybai</a></li>
      <li class="breadcrumb-item active" aria-current="page">Pasirinkti</li>
    </ol>
</nav>

<div class="container grow">
    {% comment %} product detail page with a large image on the right side and information on the left, column on mobile {% endcomment %}
    <div class="row">
        <div class="col-md-6">
            <div class="card border-0">
                <div class="card-body">
                    <hr style="border-top: 3px solid black">
                    <h4 class="card-title">{{ product.name }}</h4>
                    <p class="card-text">{{ product.description }}</p>
                    <hr style="border-top: 3px solid black">
                    <form method="POST" action="{% url 'store:order_item_endpoint' product.category.slug product.slug %}">
                    <div class="d-flex flex-column justify-content-evenly align-items-center flex-lg-row">
                        <p class="card-text align-self-center pt-4">Kaina:
                            <span class="h5">
                            {% if order_item %}
                                {{ order_item.get_total|floatformat:2 }}
                            {% else %}
                                {{ product.price|floatformat:2 }}
                            {% endif %}
                            </span> €</p>
                        <div class="form-group d-flex flex-row">
                            <label for="quantity" class="form-label mt-4">Kiekis:</label>
                            {% if order_item %}
                            <input class="form-control p-1 m-3" type="number" id="quantity" name="quantity" min="1" max="5" value="{{order_item.quantity}}">
                            <a href="{% url 'store:order_item_delete_endpoint' product.category.slug product.slug 'product' %}" class="text-dark text-decoration-none my-auto">
                                <img src="{% static 'images/logos/no-stopping.png' %}" alt="twbs" width="32px" height="32px" class="rounded-circle flex-shrink-0">
                            </a>
                            {% else %}
                            <input class="form-control p-1 m-3" type="number" id="quantity" name="quantity" min="1" max="5" value="1">
                            {% endif %}
                        </div>
                    </div>
                        <div class="d-flex justify-content-center py-lg-5 py-3">
                            {% csrf_token %}
                            <input class="btn btn-outline-primary w-100" type="submit" value="Į krepšelį">
                            <img src="{% static 'images/logos/ok-hand.svg' %}" alt="jusciogrybai" class="ms-3" width="48" height="48">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <img src="{{product.image.url}}" class="img-fluid product-img" alt="{{ product.name }}">
        </div>
    </div>
</div>
{% endblock %}

my_awesome_project/templates/store/products_by_category.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 pt-1">
        <li class="breadcrumb-item"><a href="{% url 'store:all_categories' %}">Kategorijos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Grybai</li>
    </ol>
</nav>

<div class="container text-center grow">
    <div class="row row-cols-1 row-cols-md-3 g-3 ">
        {% for product in products %}
        <div class="col">
            <div class="card border-0">
                <a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="jusciogrybai" class="card-img-top img-fluid shadow cover-img"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}